spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prototype;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: sa
    password:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    serialization:
     write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: none

management:
  context-path: /management
  security:
    enabled: false

endpoints:
  enabled: false
  health:
    enabled: true
  env:
    enabled: true
  beans:
    enabled: true
  configprops:
    enabled: true
  dump:
    enabled: true
  metrics:
    enabled: true
  trace:
    enabled: true
  loggers:
    enabled: true

flyway:
  baseline-on-migrate: true
